### ISSUE TITLE
Migrate README and /docs to antora structure

### ISSUE THREAD

**Issue by abelsromero** [asciidoctor/asciidoctor-maven-plugin#491]
As hinted in https://github.com/asciidoctor/asciidoctor.org/issues/977 we are moving to centralized site using Antora :partying_face: 

There the option to keep things in a single doc, but I think it's a good oportunity to split them. Plus, we already have a dedicated guide in _v2-migration-guide.adoc_.

High-level identified tasks are:

- [x] Build crude prototype to test
- [x] Move all documentation to an Antora structure under `docs` directory.
- [x] Create documentation modules. I am inclined to have 3:
    - ROOT: with only "welcome" _index.adoc_.
    - plugin: holding the current documentation about configuration, v2 migration.
    - project: as described in [asciidoctor/977](https://github.com/asciidoctor/asciidoctor.org/issues/977) "It only contains general information and policy documents", for example, contributing and copyright guides.
   This offers space to add future modules. For example when the doxia is split into sub-module and lifecycle-extension is integrated.

One can look at https://github.com/asciidoctor/asciidoctor.js as example.

Other minnor tasks not to forget:
- [x] Correct any reference between current docs to appropiate cross references.
- [x] Create minimal README for GitHub repo.

**Comment by abelsromero** [comment]
Crude prototype containing modules and example docs in :point_right: https://github.com/abelsromero/asciidoctor-maven-plugin/tree/poc/antora-docs.

Can be build with playbook
```
site:
  title: asciidoctor-maven-plugin docs
content:
  sources: 
  - url: asciidoctor-maven-plugin
    branches: [poc/antora-docs]
    start_path: docs
ui: 
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
```

@mojavelinux does this align with what is required?
