### ISSUE TITLE
Add anchor to configuration options in documentation

### ISSUE THREAD

**Issue by abelsromero** [asciidoctor/asciidoctor-maven-plugin#533]
Thank you for taking your time to talk with us!

**What is this issue about?**

- [ ] Bug report
- [x] Feature request
- [ ] Question

**Description**
Is not possible to share a pointer to a specific configuration option using a url. That's cumbersome because the page is relatively long so users need to navigate and then search for it by name.

**Comment by uniqueck** [comment]
Hi @abelsromero, do we have a preview site, so that i can check for working anchors?

**Comment by abelsromero** [comment]
> Hi @abelsromero, do we have a preview site, so that i can check for working anchors?

I tend to build locally installing Antora and using this config file

```
site:
  title: 'Asciidoctor docs'
content:
  sources:
    - url: .
      branches: [ YOUR BRANCH ]
      start_path: docs
asciidoc:
  attributes:
    page-pagination: ''
    idprefix: ''
    idseparator: '-'
    experimental: ''
ui:
  bundle:
    url: https://github.com/asciidoctor/docs.asciidoctor.org-ui/releases/download/prod-249/ui-bundle.zip
    snapshot: true
  supplemental_files:
    - path: ui.yml
      contents: |
        static_files: [ .nojekyll ]
    - path: .nojekyll
```
